# Machine Learning, Assignment - 10 
## <div class="alert alert-info"><b>Comparing Naive Bayes classifier and Logistic Regression classifier  on image classification of shapes.</b></div>

<div class="alert alert-info"> 1. Download a dataset from https://www.kaggle.com/cactus3/basicshapes .  (2 points) </div>

In [1]:
# copy the file path into lists

import os

categories = ['triangles','circles','squares']

path = "C:\Seetha\data\shapes\shapes\\"

fileNames = []
category = []
for c in categories:           
     new_path = path + c        
     for file in os.listdir(new_path):   
        fileNames.append(os.path.join(new_path,file)) 
        category.append(c)

print(len(fileNames))
print(len(category))

300
300


In [2]:
# load the images 

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

import numpy as np

images = [] 
for file in fileNames:    
    img = mpimg.imread(file)
#    img = rgb2gray(img)
    img = np.ravel(img)
    images.append(img)
    
print(len(images))

300


In [3]:
# Convert the images to a dataframe
import pandas as pd

df = pd.DataFrame(images)

print(df.shape)
df.head()

(300, 2352)


0     1     2     3     4     5     6     7     8     9     ...  2342  \
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
1   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
2   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
4   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   

   2343  2344  2345  2346  2347  2348  2349  2350  2351  
0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
1   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
2   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
3   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
4   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[5 rows x 2352 columns]

In [4]:
# factorise the result as 0,1,2 and append to the dataframe

labels, uniques = pd.factorize(category)

print(uniques)

df.loc[:, 'result'] = labels
df.head()

['triangles' 'circles' 'squares']


0    1    2    3    4    5    6    7    8    9  ...  2343  2344  2345  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   

   2346  2347  2348  2349  2350  2351  result  
0   1.0   1.0   1.0   1.0   1.0   1.0       0  
1   1.0   1.0   1.0   1.0   1.0   1.0       0  
2   1.0   1.0   1.0   1.0   1.0   1.0       0  
3   1.0   1.0   1.0   1.0   1.0   1.0       0  
4   1.0   1.0   1.0   1.0   1.0   1.0       0  

[5 rows x 2353 columns]

In [5]:
df.tail()

0    1    2    3    4    5    6    7    8    9  ...  2343  2344  2345  \
295  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
296  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
297  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
298  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   
299  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...   1.0   1.0   1.0   

     2346  2347  2348  2349  2350  2351  result  
295   1.0   1.0   1.0   1.0   1.0   1.0       2  
296   1.0   1.0   1.0   1.0   1.0   1.0       2  
297   1.0   1.0   1.0   1.0   1.0   1.0       2  
298   1.0   1.0   1.0   1.0   1.0   1.0       2  
299   1.0   1.0   1.0   1.0   1.0   1.0       2  

[5 rows x 2353 columns]

<div class="alert alert-info"> 2. Randomly sample the images to create training sets consisting of 70% of the  images.  Rest 30%  images form the  testing images. (1 point) </div>

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.result, test_size=0.3,
                                                    stratify = df.result, random_state=0)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(210, 2352) (90, 2352)
(210,) (90,)


<div class="alert alert-info"> 3A. Create Intensity and SVD based features </div>

In [7]:
from sklearn import decomposition

pca = decomposition.PCA(n_components=105, whiten=True)
pca.fit(X_train)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

print(X_train_pca.shape)
print(X_test_pca.shape)

(210, 105)
(90, 105)


In [8]:
from sklearn import decomposition

svd = decomposition.TruncatedSVD(n_components=105)
svd.fit(X_train)

X_train_svd = svd.transform(X_train)
X_test_svd = svd.transform(X_test)

print(X_train_svd.shape)
print(X_test_svd.shape)

(210, 105)
(90, 105)


<div class="alert alert-info"> 3B. Naive Bayes Classifier </div>

In [9]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNB.fit(X_train, y_train)
print(GNB)

y_predict = GNB.predict(X_test) 

GaussianNB(priors=None, var_smoothing=1e-09)


In [10]:
GNBpca = GaussianNB()
GNBpca.fit(X_train_pca, y_train)
print(GNBpca)

y_predict_pca = GNBpca.predict(X_test_pca) 

GaussianNB(priors=None, var_smoothing=1e-09)


In [11]:
GNBsvd =  GaussianNB()
GNBsvd.fit(X_train_svd, y_train)
print(GNBsvd)

y_predict_svd = GNBsvd.predict(X_test_svd) 

GaussianNB(priors=None, var_smoothing=1e-09)


<div class="alert alert-info"> 4. Logistic Regression Classifier </div>

In [12]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LR.fit(X_train, y_train)

y_prob  = LR.predict(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

LRpca = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LRpca.fit(X_train_pca, y_train)

y_prob_pca  = LRpca.predict(X_test_pca)

In [14]:
LRsvd = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LRsvd.fit(X_train_svd, y_train)

y_prob_svd  = LRsvd.predict(X_test_svd)

<div class="alert alert-info"> 5A. Accuracy </div>

In [15]:
from sklearn.metrics import accuracy_score

accuracy = pd.DataFrame(columns=['Classifier', 'Features', 'Accuracy'])

accuracy.loc[0] = ['Gaussian NB', 'Intensity', accuracy_score(y_test, y_predict)*100]

accuracy.loc[1] = ['Gaussian NB', 'PCA', accuracy_score(y_test, y_predict_pca)*100]

accuracy.loc[2] = ['Gaussian NB', 'SVD', accuracy_score(y_test, y_predict_svd)*100]

accuracy.loc[3] = ['Logistic Reg', 'Intensity', accuracy_score(y_test, y_prob)*100]

accuracy.loc[4] = ['Logistic Reg', 'PCA', accuracy_score(y_test, y_prob_pca)*100]

accuracy.loc[5] = ['Logistic Reg', 'SVD', accuracy_score(y_test, y_prob_svd)*100]

print(accuracy)

     Classifier   Features   Accuracy
0   Gaussian NB  Intensity  38.888889
1   Gaussian NB        PCA  50.000000
2   Gaussian NB        SVD  48.888889
3  Logistic Reg  Intensity  48.888889
4  Logistic Reg        PCA  45.555556
5  Logistic Reg        SVD  46.666667


<div class="alert alert-info"> 5B. Confusion Matrix </div>

In [16]:
from sklearn.metrics import confusion_matrix 

conf_matrix = confusion_matrix(y_test, y_predict) 
print('Confusion Matrix Gaussian NB Intensity:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_predict_pca) 
print('Confusion Matrix Gaussian NB PCA:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_predict_svd) 
print('Confusion Matrix Gaussian NB SVD:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob) 
print('Confusion Matrix Logistic Regression Intensity:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob_pca) 
print('Confusion Matrix Logistic Regression PCA:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob_svd) 
print('Confusion Matrix Logistic Regression SVD:', )
print(conf_matrix)

Confusion Matrix Gaussian NB Intensity:
[[20  5  5]
 [20  7  3]
 [15  7  8]]
Confusion Matrix Gaussian NB PCA:
[[12  9  9]
 [ 3 17 10]
 [ 4 10 16]]
Confusion Matrix Gaussian NB SVD:
[[11 11  8]
 [ 1 16 13]
 [ 2 11 17]]
Confusion Matrix Logistic Regression Intensity:
[[16  8  6]
 [ 4 16 10]
 [ 9  9 12]]
Confusion Matrix Logistic Regression PCA:
[[16  8  6]
 [ 8 15  7]
 [ 9 11 10]]
Confusion Matrix Logistic Regression SVD:
[[18  7  5]
 [ 7 13 10]
 [ 8 11 11]]


<div class="alert alert-info"> 6. Compare the performance of the  above classifiers and report your observations. (2 points) </div>

From the reported accuracies,
Gaussian Naive Bayes Classifier with PCA is showing better accuracy.
