# Machine Learning, Assignment - 8 
## <div class="alert alert-info"><b>Comparing Naive Bayes classifier and Logistic Regression classifier  on image classification of face.</b></div>

<div class="alert alert-info"> 1. Download a dataset from https://github.com/StephenMilborrow/muct . Group the images into male and female categories based on the images. (2 points) </div>

In [1]:
# copy the file path into lists

import os

categories = ['Female','Male']

path = "C:\Seetha\data\muct-a-jpg\\"

fileNames = []
category = []
for c in categories:           
     new_path = path + c        
     for file in os.listdir(new_path):   
        fileNames.append(os.path.join(new_path,file)) 
        category.append(c)

print(len(fileNames))
print(len(category))

751
751


In [2]:
# load the images 

from PIL import Image

import numpy as np

images = [] 
for file in fileNames:    
    img = Image.open(file).convert('LA')
    img = img.resize((28, 28))
    img = np.ravel(img)
    images.append(img)
    
print(len(images))

751


In [3]:
# Convert the images to a dataframe
import pandas as pd

df = pd.DataFrame(images)

print(df.shape)
df.head()

(751, 1568)


0     1     2     3     4     5     6     7     8     9     ...  1558  \
0   111   255   114   255   114   255   113   255   118   255  ...    50   
1   113   255   118   255   116   255   117   255   116   255  ...    42   
2   163   255   167   255   166   255   168   255   171   255  ...    77   
3   110   255   111   255   111   255   108   255   116   255  ...   110   
4   114   255   118   255   117   255   117   255   116   255  ...   102   

   1559  1560  1561  1562  1563  1564  1565  1566  1567  
0   255    66   255    48   255    68   255    48   255  
1   255    42   255    51   255    74   255    86   255  
2   255    74   255    68   255    67   255   102   255  
3   255   101   255   112   255   105   255   107   255  
4   255    92   255   104   255    97   255   103   255  

[5 rows x 1568 columns]

In [4]:
# factorise the result as 0,1,2 and append to the dataframe

labels, uniques = pd.factorize(category)

print(uniques)

df.loc[:, 'Category'] = labels

df.head()

['Female' 'Male']


0    1    2    3    4    5    6    7    8    9  ...  1559  1560  1561  \
0  111  255  114  255  114  255  113  255  118  255  ...   255    66   255   
1  113  255  118  255  116  255  117  255  116  255  ...   255    42   255   
2  163  255  167  255  166  255  168  255  171  255  ...   255    74   255   
3  110  255  111  255  111  255  108  255  116  255  ...   255   101   255   
4  114  255  118  255  117  255  117  255  116  255  ...   255    92   255   

   1562  1563  1564  1565  1566  1567  Category  
0    48   255    68   255    48   255         0  
1    51   255    74   255    86   255         0  
2    68   255    67   255   102   255         0  
3   112   255   105   255   107   255         0  
4   104   255    97   255   103   255         0  

[5 rows x 1569 columns]

In [5]:
df.tail()

0    1    2    3    4    5    6    7    8    9  ...  1559  1560  1561  \
746   60  255   61  255   61  255   61  255   62  255  ...   255   125   255   
747  106  255  106  255  104  255  106  255  107  255  ...   255   183   255   
748   61  255   60  255   59  255   61  255   60  255  ...   255   143   255   
749  105  255  106  255  104  255  105  255  107  255  ...   255    88   255   
750   61  255   60  255   61  255   62  255   63  255  ...   255    67   255   

     1562  1563  1564  1565  1566  1567  Category  
746   127   255   120   255   104   255         1  
747   185   255   182   255   182   255         1  
748   145   255   148   255   144   255         1  
749    94   255   120   255   119   255         1  
750    75   255    53   255    66   255         1  

[5 rows x 1569 columns]

<div class="alert alert-info"> 2. Randomly sample the images to create training sets consisting of 70% of the  images.  Rest 30%  images form the  testing images. (1 point) </div>

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.Category, test_size=0.3,
                                                    stratify = df.Category, random_state=0)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(525, 1568) (226, 1568)
(525,) (226,)


<div class="alert alert-info"> 3A. Create Intensity based features </div>

intensity based features are using the X_train and Y_test as such.

In [7]:

# PCA based features

from sklearn import decomposition

pca = decomposition.PCA(n_components=100, whiten=True)
pca.fit(X_train)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

print(X_train_pca.shape)
print(X_test_pca.shape)

(525, 100)
(226, 100)


<div class="alert alert-info"> 3B. Create SVD based features </div>

In [8]:
from sklearn import decomposition

svd = decomposition.TruncatedSVD(n_components=100)
svd.fit(X_train)

X_train_svd = svd.transform(X_train)
X_test_svd = svd.transform(X_test)

print(X_train_svd.shape)
print(X_test_svd.shape)

(525, 100)
(226, 100)


<div class="alert alert-info"> 3C. Naive Bayes Classifier </div>

In [9]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNB.fit(X_train, y_train)
print(GNB)

y_predict = GNB.predict(X_test) 

GaussianNB(priors=None, var_smoothing=1e-09)


In [10]:
GNBpca = GaussianNB()
GNBpca.fit(X_train_pca, y_train)
print(GNBpca)

y_predict_pca = GNBpca.predict(X_test_pca) 

GaussianNB(priors=None, var_smoothing=1e-09)


In [11]:
GNBsvd =  GaussianNB()
GNBsvd.fit(X_train_svd, y_train)
print(GNBsvd)

y_predict_svd = GNBsvd.predict(X_test_svd) 

GaussianNB(priors=None, var_smoothing=1e-09)


<div class="alert alert-info"> 4. Logistic Regression Classifier </div>

In [12]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LR.fit(X_train, y_train)

y_prob  = LR.predict(X_test)

In [13]:
LRpca = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LRpca.fit(X_train_pca, y_train)

y_prob_pca  = LRpca.predict(X_test_pca)

In [14]:
LRsvd = LogisticRegression(solver='liblinear', multi_class = 'auto') # default classfier

LRsvd.fit(X_train_svd, y_train)

y_prob_svd  = LRsvd.predict(X_test_svd)

<div class="alert alert-info"> 5A. Accuracy </div>

In [15]:
from sklearn.metrics import accuracy_score

accuracy = pd.DataFrame(columns=['Classifier', 'Features', 'Accuracy'])

accuracy.loc[0] = ['Gaussian NB', 'Intensity', accuracy_score(y_test, y_predict)*100]

accuracy.loc[1] = ['Gaussian NB', 'PCA', accuracy_score(y_test, y_predict_pca)*100]

accuracy.loc[2] = ['Gaussian NB', 'SVD', accuracy_score(y_test, y_predict_svd)*100]

accuracy.loc[3] = ['Logistic Reg', 'Intensity', accuracy_score(y_test, y_prob)*100]

accuracy.loc[4] = ['Logistic Reg', 'PCA', accuracy_score(y_test, y_prob_pca)*100]

accuracy.loc[5] = ['Logistic Reg', 'SVD', accuracy_score(y_test, y_prob_svd)*100]

print(accuracy)

     Classifier   Features   Accuracy
0   Gaussian NB  Intensity  73.008850
1   Gaussian NB        PCA  76.991150
2   Gaussian NB        SVD  77.876106
3  Logistic Reg  Intensity  88.053097
4  Logistic Reg        PCA  87.168142
5  Logistic Reg        SVD  84.955752


<div class="alert alert-info"> 5B. Confusion Matrix </div>

In [16]:
from sklearn.metrics import confusion_matrix 

conf_matrix = confusion_matrix(y_test, y_predict) 
print('Confusion Matrix Gaussian NB Intensity:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_predict_pca) 
print('Confusion Matrix Gaussian NB PCA:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_predict_svd) 
print('Confusion Matrix Gaussian NB SVD:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob) 
print('Confusion Matrix Logistic Regression Intensity:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob_pca) 
print('Confusion Matrix Logistic Regression PCA:', )
print(conf_matrix)

conf_matrix = confusion_matrix(y_test, y_prob_svd) 
print('Confusion Matrix Logistic Regression SVD:', )
print(conf_matrix)

Confusion Matrix Gaussian NB Intensity:
[[89 26]
 [35 76]]
Confusion Matrix Gaussian NB PCA:
[[110   5]
 [ 47  64]]
Confusion Matrix Gaussian NB SVD:
[[111   4]
 [ 46  65]]
Confusion Matrix Logistic Regression Intensity:
[[107   8]
 [ 19  92]]
Confusion Matrix Logistic Regression PCA:
[[104  11]
 [ 18  93]]
Confusion Matrix Logistic Regression SVD:
[[102  13]
 [ 21  90]]


<div class="alert alert-info"> 6. Compare the performance of the  above classifiers and report your observations. (2 points) </div>

From the reported accuracies,

Logistic Regression is better than Gaussian Naive Bayes Classifier .

When using Gaussian Naive Bayes  classifier SVD gives a better accuracy.