# Machine Learning, Assignment - 6 
## <div class="alert alert-info"><b>Spam filtering</b></div>

<div class="alert alert-info"> Spam filtering is an example of document classification task which involves classifying an email / SMS as spam or non-spam (a.k.a. ham). </div>


<div class="alert alert-info"> 1. Import the dataset from https://www.kaggle.com/uciml/sms-spam-collection-dataset. (1 point). </div>



In [6]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("C:\Seetha\data\spambase.data",delimiter=",",header=None)

print(dataset.shape)

dataset[:5]



(4601, 58)


0     1     2    3     4     5     6     7     8     9   ...    48  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   

      49   50     51     52     53     54   55    56  57  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  

[5 rows x 58 columns]

<div class="alert alert-info"> 2. Split the data into training and testing. (1 point) Optionally you can use 10-fold cross validation. </div>

In [8]:
x = dataset.iloc[:,:56] 

y = dataset.iloc[:,-1]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(x, y, test_size = 0.33, random_state = 17)

<div class="alert alert-info"> 3. Extract features using TF-IDF and display the features. ( 2 points)</div>

This step not required as dataset is already given the score.

<div class="alert alert-info"> 4. Model the classifier using GaussianNB, BernoulliNB and MultinomialNB.  </div>

<div class="alert alert-info"> 5. Train the classifiers.( 3 points) </div>

In [9]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB


BernNB = BernoulliNB(binarize=True)
BernNB.fit(x_train,y_train)
print(BernNB)

GaussNB = GaussianNB()
GaussNB.fit(x_train,y_train)
print(GaussNB)

MultiNB = MultinomialNB()
MultiNB.fit(x_train,y_train)
print(MultiNB)

BernoulliNB(alpha=1.0, binarize=True, class_prior=None, fit_prior=True)
GaussianNB(priors=None, var_smoothing=1e-09)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


<div class="alert alert-info"> 6. Evaluate classifiers on Test Data. ( 2 points) </div>

In [10]:
from sklearn.metrics import accuracy_score

y_predict = BernNB.predict(x_test)
print('BernoulliNB', accuracy_score(y_test,y_predict)*100)


y_predict = GaussNB.predict(x_test)
print('GaussianNB', accuracy_score(y_test,y_predict)*100)


y_predict = MultiNB.predict(x_test)
print('MultinomialNB', accuracy_score(y_test,y_predict)*100)

BernoulliNB 86.57011191573403
GaussianNB 82.29098090849243
MultinomialNB 84.13429888084266


<div class="alert alert-info"> 7. Report the classifier accuracy, polarity score for each sentence for all the classifiers. For example, this paragraph has probability of 60% being spam or vice versa. ( 2 points) </div>

In [15]:
# predict_proba() function of sklearn library for any model like Logistic or Naive Bayes
# would give probability scores of both classes.
print('Bernnoulli NB')
print(BernNB.predict_proba(x_test))

print('Gaussuan NB')
print(GaussNB.predict_proba(x_test))

print('Multinomial NB')
print(MultiNB.predict_proba(x_test))

Bernnoulli NB
[[0.01431819 0.98568181]
 [0.13046915 0.86953085]
 [0.00193843 0.99806157]
 ...
 [0.58575694 0.41424306]
 [0.94475149 0.05524851]
 [0.00163861 0.99836139]]
Gaussuan NB
[[2.68572100e-041 1.00000000e+000]
 [1.18159389e-021 1.00000000e+000]
 [1.71494793e-034 1.00000000e+000]
 ...
 [9.99939583e-001 6.04170378e-005]
 [1.00000000e+000 1.37091201e-237]
 [8.67219456e-048 1.00000000e+000]]
Multinomial NB
[[3.19763966e-09 9.99999997e-01]
 [4.52911250e-01 5.47088750e-01]
 [1.83497071e-31 1.00000000e+00]
 ...
 [2.41584389e-01 7.58415611e-01]
 [1.00000000e+00 8.03456998e-11]
 [6.87158283e-03 9.93128417e-01]]


<div class="alert alert-info"> 8. Display and visualize the word cloud of both the classes. For example, Display word clouds for Spam vs Legitimate word clouds. It should show the frequent words coming in respective classes. ( 2 points)</div>

In [ ]:
from wordcloud import WordCloud, STOPWORDS

def generate_word_cloud(text):
    stopwords = STOPWORDS
    wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)    
    #storing the wordcloud in image "wc.png"
    wordcloud.to_file('static/wc.png')
    return 'wc.png'

This step not required as score is already given, not text.