# Logistic Regression for Multiclass classification

<b>Logistic model</b>  is used to model the probability of a certain class or event existing such as pass/fail, win/lose, alive/dead or healthy/sick.

A <b>binary logistic model</b> has a dependent variable with two possible values, such as pass/fail which is represented by labels 1/0. 

<div align="right">   Reference: Wikipedia </div> 

In this session, we will perform multinomial classification by using logistic regression model. It is also known as Softmax Classification.

## 1. Import necessary libraries

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

## 2. Import and preprocess the dataset

Iris dataset consists of 150 observations.

The features or attributed (columns) are Sepal Length, Sepal Width, Petal Length and Petal Width.

The observations (rows) belong to 3 different types of iris species - Setosa, Versicolour, and Virginica. Each class has 50 observations.

The iris dataset can be downloded from Kaggle: https://www.kaggle.com/uciml/iris as csv file.


In [2]:
# Load Iris dataset.

iris = load_iris()

# Extract two columns from the dataset for X values.
# X is  petal length, petal width.
# y is the target column.

X = iris["data"][:,(2,3)]  
y = iris["target"]

In [3]:
# Split data into train and test

(X_train, X_test, y_train, y_test) = train_test_split(X, y, stratify=y, test_size= 0.3)


## 3. Create and train the machine learning model

In [4]:
# build the model

model_softmax = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=5) 
# default values are used

model_softmax.fit(X_train,y_train) # train

LogisticRegression(C=5, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

## 4. Make Predictions

In [5]:
# predict the values

y_prob  = model_softmax.predict(X_test)


## 5. Performance measures

In [9]:
acc = accuracy_score(y_test, y_prob)
print(acc * 100)

97.77777777777777


In [7]:
from sklearn.metrics import confusion_matrix 

conf_matrix = confusion_matrix(y_test, y_prob) 
print('Confusion Matrix :')
print(conf_matrix)


Confusion Matrix :
[[15  0  0]
 [ 0 14  1]
 [ 0  0 15]]


In [8]:
from sklearn.metrics import classification_report 

print('Classification Report:')
print(classification_report(y_test, y_prob))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        15

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

